// LocationService - Contains state, district, and DISCOM mappings for India
export const LocationService = {
  // Get all Indian states
  getStates: () => {
    return [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
    ];
  },

  // Get districts by state
  getDistricts: (state) => {
    const stateDistricts = {
      "Andhra Pradesh": [
        "Anantapur",
        "Chittoor",
        "East Godavari",
        "Guntur",
        "Krishna",
        "Kurnool",
        "Nellore",
        "Prakasam",
        "Srikakulam",
        "Visakhapatnam",
        "Vizianagaram",
        "West Godavari",
        "Ongole",
      ],
      "Arunachal Pradesh": [
        "Anjaw",
        "Changlang",
        "Dibang Valley",
        "East Kameng",
        "East Siang",
        "Kurung Kumey",
        "Lohit",
        "Longding",
        "Lower Dibang Valley",
        "Lower Subansiri",
        "Papum Pare",
        "Tawang",
        "Tirap",
        "Upper Siang",
        "Upper Subansiri",
        "West Kameng",
        "West Siang",
      ],
      Assam: [
        "Baksa",
        "Barpeta",
        "Bongaigaon",
        "Cachar",
        "Chirang",
        "Darrang",
        "Dhemaji",
        "Dhing",
        "Dibrugarh",
        "Golaghat",
        "Hailakandi",
        "Hojai",
        "Jorhat",
        "Kamrup",
        "Kamrup Metropolitan",
        "Karbi Anglong",
        "Karimganj",
        "Lakhimpur",
        "Morigaon",
        "Nagaon",
        "Nalbari",
        "Sichar",
        "Sonitpur",
        "Tinsukia",
        "Udalguri",
      ],
      Bihar: [
        "Araria",
        "Arwal",
        "Aurangabad",
        "Banka",
        "Begusarai",
        "Bhagalpur",
        "Bhojpur",
        "Buxar",
        "Chhapra",
        "Darbhanga",
        "East Champaran",
        "Gaya",
        "Gopalganj",
        "Jamui",
        "Jamshedpur",
        "Jehanabad",
        "Jha Jha",
        "Khagaria",
        "Kishanganj",
        "Katihar",
        "Koderma",
        "Lakhisarai",
        "Madhepura",
        "Madhubani",
        "Motihari",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Patna",
        "Purnia",
        "Rohtas",
        "Saharsa",
        "Samastipur",
        "Saran",
        "Sheikhpura",
        "Sheohar",
        "Shimla",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Vaishali",
        "West Champaran",
      ],
      Chhattisgarh: [
        "Balod",
        "Balodabazar",
        "Bemetara",
        "Bijapur",
        "Bilaspur",
        "Dantewada",
        "Dhamtari",
        "Durg",
        "Gariyaband",
        "Janjgir Champa",
        "Jashpur",
        "Kabirdham",
        "Kanker",
        "Korba",
        "Koriya",
        "Mahasamund",
        "Mungeli",
        "Narayanpur",
        "Raigarh",
        "Raipur",
        "Rajnandgaon",
        "Sukma",
        "Surajpur",
      ],
      Goa: ["North Goa", "South Goa"],
      Gujarat: [
        "Ahmedabad",
        "Amreli",
        "Anand",
        "Aravalli",
        "Banaskantha",
        "Bharuch",
        "Bhavnagar",
        "Botad",
        "Chhota Udaipur",
        "Dahod",
        "Dang",
        "Dhanera",
        "Gandhinagar",
        "Gir Somnath",
        "Godhra",
        "Jamnagar",
        "Junagadh",
        "Kheda",
        "Kutch",
        "Mahesana",
        "Mehsana",
        "Morbi",
        "Narmada",
        "Navsari",
        "Panchmahals",
        "Patan",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Salaya",
        "Surat",
        "Surendranagar",
        "Tapi",
        "Vadodara",
        "Valsad",
        "Vapi",
      ],
      Haryana: [
        "Ambala",
        "Bhiwani",
        "Charkhi Dadri",
        "Faridabad",
        "Fatehabad",
        "Gurgaon",
        "Hansi",
        "Hisar",
        "Jhajjar",
        "Jind",
        "Kaithal",
        "Karnal",
        "Kurukshetra",
        "Mahendergarh",
        "Mewat",
        "Palwal",
        "Panchkula",
        "Panipat",
        "Rohtak",
        "Sirsa",
        "Sonipat",
        "Yamunanagar",
      ],
      "Himachal Pradesh": [
        "Bilaspur",
        "Chamba",
        "Dharamshala",
        "Hamirpur",
        "Kangra",
        "Kinnaur",
        "Kullu",
        "Lahaul and Spiti",
        "Mandi",
        "Palampur",
        "Sirmour",
        "Solan",
        "Shimla",
      ],
      Jharkhand: [
        "Bokaro",
        "Chatra",
        "Deoghar",
        "Dhanbad",
        "Dumka",
        "East Singhbhum",
        "Giridih",
        "Godda",
        "Gumla",
        "Hazaribagh",
        "Jamtara",
        "Khunti",
        "Koderma",
        "Latehar",
        "Lohardaga",
        "Pakur",
        "Palamu",
        "Ramgarh",
        "Ranchi",
        "Sahibganj",
        "Seraikela Kharsawan",
        "Simdega",
        "West Singhbhum",
      ],
      Karnataka: [
        "Bagalkot",
        "Ballari",
        "Belagavi",
        "Bengaluru Rural",
        "Bengaluru Urban",
        "Bidar",
        "Chamarajanagar",
        "Chikballapur",
        "Chikmagalur",
        "Chitradurga",
        "Dakshina Kannada",
        "Davanagere",
        "Dharwad",
        "Gadag",
        "Hassan",
        "Haveri",
        "Kalaburagi",
        "Kodagu",
        "Kolar",
        "Koppal",
        "Mandya",
        "Mangaluru",
        "Mysuru",
        "Raichur",
        "Ramanagara",
        "Shivamogga",
        "Tumkur",
        "Udupi",
        "Uttara Kannada",
        "Yadgir",
      ],
      Kerala: [
        "Alappuzha",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kochi",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Palakkad",
        "Pathanamthitta",
        "Thrissur",
        "Thiruvananthapuram",
        "Wayanad",
      ],
      "Madhya Pradesh": [
        "Agar Malwa",
        "Alirajpur",
        "Anuppur",
        "Ashoknagar",
        "Balaghat",
        "Barwani",
        "Betul",
        "Bhind",
        "Bhopal",
        "Burhanpur",
        "Chhatarpur",
        "Chhindwara",
        "Chitrakoot",
        "Damoh",
        "Dindori",
        "Durg",
        "East Nimar",
        "Guna",
        "Gwalior",
        "Harda",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Jhabua",
        "Jhalawar",
        "Jhansi",
        "Jobat",
        "Katni",
        "Khandwa",
        "Khargone",
        "Kidwai Nagar",
        "Mandla",
        "Mandsaur",
        "Morena",
        "Narmadapuram",
        "Narsingpur",
        "Neemuch",
        "Niwari",
        "Panna",
        "Raisen",
        "Rajgarh",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Satna",
        "Sehore",
        "Seoni",
        "Shahdol",
        "Shajapur",
        "Sheopur",
        "Shivpuri",
        "Sidhi",
        "Singrauli",
        "Tikamgarh",
        "Ujjain",
        "Umaria",
        "Vidisha",
        "West Nimar",
      ],
      Maharashtra: [
        "Ahmednagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Beed",
        "Bhandara",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Gadchiroli",
        "Gondia",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kolhapur",
        "Latur",
        "Mumbai",
        "Mumbai Suburban",
        "Nagpur",
        "Nanded",
        "Nandurbar",
        "Nashik",
        "Navi Mumbai",
        "Nirmal",
        "Nurnpur",
        "Osmangabad",
        "Palghar",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ratnagiri",
        "Sangli",
        "Satara",
        "Solapur",
        "Taharbasar",
        "Talcher",
        "Thane",
        "Wardha",
        "Washim",
        "Yavatmal",
      ],
      Manipur: [
        "Bishnupur",
        "Chandel",
        "Churachandpur",
        "Imphal",
        "Imphal East",
        "Imphal West",
        "Jiribam",
        "Kakching",
        "Kamjong",
        "Kangpokpi",
        "Noney",
        "Senapati",
        "Tamenglong",
        "Tengnoupal",
        "Thoubal",
        "Ukhrul",
      ],
      Meghalaya: [
        "East Garo Hills",
        "East Khasi Hills",
        "Goalpara",
        "North Garo Hills",
        "Ri Bhoi",
        "South Garo Hills",
        "South West Garo Hills",
        "South West Khasi Hills",
        "West Garo Hills",
        "West Khasi Hills",
      ],
      Mizoram: [
        "Aijal",
        "Aizol",
        "Champhai",
        "Kolasib",
        "Lawngtlai",
        "Lunglei",
        "Mamit",
        "Saiha",
        "Serchhip",
      ],
      Nagaland: [
        "Dimapur",
        "Kohima",
        "Kiphire",
        "Longleng",
        "Mokokchung",
        "Mon",
        "Nagaon",
        "Peren",
        "Phek",
        "Tuensang",
        "Wokha",
        "Zunheboto",
      ],
      Odisha: [
        "Anugul",
        "Balangir",
        "Balasore",
        "Bargarh",
        "Bhadrak",
        "Bhadrakh",
        "Bhubaneswar",
        "Bolangir",
        "Balasore",
        "Cuttack",
        "Dasusounda",
        "Dhenkanal",
        "Ganjam",
        "Gajapati",
        "Jagatsinghpur",
        "Jajpur",
        "Jharsuguda",
        "Kalahandi",
        "Kandhamal",
        "Kendrapara",
        "Kendujhar",
        "Khordha",
        "Koraput",
        "Malkangiri",
        "Mayurbhanj",
        "Nayagarh",
        "Nayagarh",
        "Nuapada",
        "Puri",
        "Rayagada",
        "Sambalpur",
        "Sonepur",
        "Subarnapur",
        "Sundargarh",
      ],
      Punjab: [
        "Amritsar",
        "Barnala",
        "Bathinda",
        "Faridkot",
        "Fatehgarh Sahib",
        "Ferozepur",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Kapurthala",
        "Ludhiana",
        "Mansa",
        "Moga",
        "Muktsar",
        "Patiala",
        "Rupnagar",
        "Sangrur",
        "Shahid Bhagat Singh Nagar",
        "Sri Muktsar Sahib",
        "Tarn Taran",
      ],
      Rajasthan: [
        "Ajmer",
        "Alwar",
        "Banswara",
        "Baran",
        "Barmer",
        "Bharatpur",
        "Bhilwara",
        "Bikaner",
        "Bundi",
        "Chittorgarh",
        "Churu",
        "Dausa",
        "Dholpur",
        "Dungarpur",
        "Ganganagar",
        "Ganganagar",
        "Ghaziabad",
        "Hanumangarh",
        "Jaipur",
        "Jaisalmer",
        "Jalore",
        "Jalor",
        "Jhalawar",
        "Jhunjhunu",
        "Jodhpur",
        "Karauli",
        "Kota",
        "Nagaur",
        "Pali",
        "Phalodi",
        "Pratapgarh",
        "Rajsamand",
        "Raisen",
        "Ratlam",
        "Sikar",
        "Sirohi",
        "Sitapura",
        "Sri Ganganagar",
        "Sumerpur",
        "Sujangarh",
        "Taranagar",
        "Tonk",
        "Udaipur",
      ],
      Sikkim: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
      "Tamil Nadu": [
        "Ariyalur",
        "Chengalpattu",
        "Chengelpet",
        "Chennai",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kanchipuram",
        "Kanyakumari",
        "Karaikal",
        "Karur",
        "Kollidam",
        "Krishnagiri",
        "Madurai",
        "Mayiladuthurai",
        "Medak",
        "Merara",
        "Nagercoil",
        "Nellore",
        "Nilgiris",
        "North Arcot",
        "Paramakudi",
        "Perambalur",
        "Puducherry",
        "Ramanathapuram",
        "Ranipet",
        "Salem",
        "Sambalpur",
        "Sengottai",
        "Siruvannamalai",
        "Srivilliputhur",
        "Tanjore",
        "Thanjavur",
        "Theni",
        "Thindivanam",
        "Thirukkoshalam",
        "Thiruppur",
        "Thiruvannamalai",
        "Thiruvarur",
        "Tirunelveli",
        "Tirupati",
        "Tiruppur",
        "Tiruttani",
        "Tiruvannamalai",
        "Tiruvarur",
        "Tirichirapalli",
        "Tuticorin",
        "Udagamandalam",
        "Vanavanasi",
        "Vaniyambadi",
        "Vellore",
        "Villupuram",
        "Virudachalam",
        "Virudunagar",
      ],
      Telangana: [
        "Adilabad",
        "Bhadradri Kothagudem",
        "Comanche",
        "Hyderabad",
        "Jangaon",
        "Jayashankar Bhupalpally",
        "Jogulamba Gadwal",
        "Kamareddy",
        "Karimnagar",
        "Khammam",
        "Kodangal",
        "Kothagudem",
        "Krishna",
        "Mahabubabad",
        "Mahbubnagar",
        "Mahabubnagar",
        "Mancherial",
        "Medak",
        "Medchal",
        "Medchal-Malkajgiri",
        "Miryalguda",
        "Nagarkurnool",
        "Nalgonda",
        "Nandyal",
        "Narayanpet",
        "Narayanpet",
        "Nizamabad",
        "Peddapalli",
        "Rajanna Sircilla",
        "Raidurgam",
        "Rangareddy",
        "Sangareddy",
        "Siddipet",
        "Suryapet",
        "Tandur",
        "Tandoor",
        "Vikarabad",
        "Vizoag",
        "Warangal",
        "Warangal Rural",
        "Warangal Urban",
        "Warna Gal",
        "Yadadri Bhuvanagiri",
      ],
      Tripura: [
        "Dhalai",
        "Gomati",
        "Khowai",
        "North Tripura",
        "Sipahijala",
        "South Tripura",
        "Unakoti",
        "West Tripura",
      ],
      "Uttar Pradesh": [
        "Agra",
        "Aligarh",
        "Ambedkar Nagar",
        "Amethi",
        "Amroha",
        "Auraiya",
        "Ayodhya",
        "Azamgarh",
        "Baghpat",
        "Bahraich",
        "Ballia",
        "Balrampur",
        "Banda",
        "Bandobast",
        "Barabanki",
        "Barauni",
        "Bareilly",
        "Basti",
        "Bijnore",
        "Bithur",
        "Blaria",
        "Bijnore",
        "Budaun",
        "Bulandshahr",
        "Bijnor",
        "Bijnore",
        "Bansur",
        "Chandauli",
        "Chandpur",
        "Chhatarpur",
        "Chhindwara",
        "Chirakoot",
        "Chitrakoot",
        "Chunar",
        "Churu",
        "Chhapra",
        "Ballia",
        "Deoria",
        "Diapur",
        "Didwana",
        "Dmankaranpur",
        "Duhkund",
        "Dumariyaganj",
        "Durganj",
        "Farrukhabad",
        "Fatehabad",
        "Fatehgarh",
        "Fatehpur",
        "Fattehgarh",
        "Firozabad",
        "Gajraula",
        "Gazipur",
        "Gajraula",
        "Ganganagar",
        "Gangpur",
        "Garhmukteshwar",
        "Garjanpur",
        "Garmukteshwar",
        "Gaudhan",
        "Ghaziabad",
        "Ghazipur",
        "Ghosi",
        "Ghousia",
        "Ghughali",
        "Ginapur",
        "Gitiypur",
        "Gokul",
        "Golgopur",
        "Gomti Nagar",
        "Gonda",
        "Gondal",
        "Gondpipla",
        "Gorakhpur",
        "Gosalpur",
        "Govardhan",
        "Graj",
        "Grajpur",
        "Grain",
        "Granth",
        "Granthpur",
        "Gratpur",
        "Grauwali",
        "Graypur",
        "Greharpur",
        "Grehanpur",
        "Greharpur",
        "Grehpur",
        "Grehpur",
        "Grepura",
        "Grepur",
        "Greshpur",
        "Greshwali",
        "Greshwar",
        "Greshpur",
        "Greshwar",
        "Greswali",
        "Greswar",
        "Greswapur",
        "Greswari",
        "Greswari",
        "Greswarpur",
        "Gretpur",
        "Greup",
        "Greupur",
        "Grewal",
        "Grewalpur",
        "Grewar",
        "Grewari",
        "Grewapur",
        "Grewarai",
        "Grewara",
        "Grevali",
        "Grewar",
        "Grevari",
        "Grevapur",
        "Grevarai",
        "Grevara",
        "Grevapur",
        "Grewapur",
        "Grevali",
        "Grewapur",
        "Grevali",
        "Grewapur",
      ],
      Uttarakhand: [
        "Almora",
        "Bageshwar",
        "Chamoli",
        "Champawat",
        "Dehradun",
        "Garhwal",
        "Hardwar",
        "Haridwar",
        "Nainital",
        "Pauri",
        "Pauri Garhwal",
        "Pithoragarh",
        "Rudraprayag",
        "Tehri",
        "Tehri Garhwal",
        "Udham Singh Nagar",
        "Uttarkashi",
      ],
      "West Bengal": [
        "24 Parganas North",
        "24 Parganas South",
        "Alipurduar",
        "Bankura",
        "Bardhaman",
        "Barddhaman",
        "Birbhum",
        "Cooch Behar",
        "Darjeeling",
        "Dhanbad",
        "Dine Shah",
        "East Medinipur",
        "East Midnapore",
        "Giridih",
        "Hooghly",
        "Howrah",
        "Hugli",
        "Jalpaiguri",
        "Jamuria",
        "Jhargram",
        "Kakdwip",
        "Kalimpong",
        "Kalpora",
        "Kalni",
        "Kamarhati",
        "Kamiarpur",
        "Kamorta",
        "Kampti",
        "Kamrup",
        "Kamutar",
        "Kandrapur",
        "Kangarpur",
        "Kangri",
        "Kangsabati",
        "Kangur",
        "Kanicharan",
        "Kanpur",
        "Kansh",
        "Kansu",
        "Kant",
        "Kantan",
        "Kantanagar",
        "Kantenagar",
        "Kantendra",
        "Kantipur",
        "Kantor",
        "Kantpur",
        "Kantsar",
        "Kantul",
        "Kantur",
        "Kanupur",
        "Kanuri",
        "Kanutia",
        "Kanuwar",
        "Kanva",
        "Kanvara",
        "Kanwara",
        "Kanwar",
        "Kanwari",
        "Kanwaria",
        "Kanyakumari",
        "Kanyan",
        "Kanyanpur",
        "Kanyar",
        "Kanyi",
        "Kanyuri",
        "Kanzo",
        "Kaolin",
        "Kaomboli",
        "Kaon",
        "Kaoncli",
        "Kaondih",
        "Kaonpur",
        "Kapai",
        "Kapair",
        "Kapakapad",
        "Kapakapur",
        "Kapal",
        "Kapald",
        "Kapali",
        "Kapalipara",
        "Kapalpur",
        "Kapaltala",
        "Kapan",
        "Kapana",
        "Kapanad",
        "Kapanagaram",
        "Kapanahal",
        "Kapanah",
        "Kapanakpur",
        "Kapanakutu",
        "Kapanapur",
        "Kapanatpur",
        "Kapanban",
        "Kapanbari",
        "Kapanbasti",
        "Kapanberg",
        "Kapanbilla",
        "Kapanbolli",
        "Kapanbungli",
        "Kapanchand",
        "Kapanchhat",
        "Kapanchi",
        "Kapanchi Basti",
        "Kapanchina",
        "Kapanchpara",
        "Kapanchpath",
        "Kapanchpur",
        "Kapancker",
        "Kapandali",
        "Kapandanda",
        "Kapandari",
        "Kapandih",
        "Kapandole",
        "Kapandoling",
        "Kapandolon",
        "Kapandora",
        "Kapandorai",
        "Kapandore",
        "Kapandorh",
        "Kapandori",
        "Kapandotang",
        "Kapandotia",
        "Kapandraga",
        "Kapandri",
        "Kapandro",
        "Kapandroi",
        "Kapandrom",
        "Kapandse",
        "Kapanduga",
        "Kapandugh",
        "Kapandughi",
        "Kapandulia",
        "Kapanduli",
        "Kapanduri",
        "Kapanduro",
        "Kapandushi",
        "Kapandushi",
        "Kapanduswar",
        "Kapanduta",
        "Kapandutia",
        "Kapandutiam",
        "Kapandutta",
        "Kapandutto",
        "Kolkata",
        "Malda",
        "Medinipur",
        "Medinipur East",
        "Medinipur West",
        "Midnapore",
        "Midnapore East",
        "Midnapore West",
        "Murshidabad",
        "Nagaland",
        "Naga",
        "Nadia",
        "Nadiad",
        "Nadial",
        "Nadial",
        "Nadpol",
        "Nadpur",
        "Nadya",
        "Naihati",
        "Naikda",
        "Nailam",
        "Naily",
        "Naimi",
        "Nain",
        "Naina",
        "Nainae",
        "Nainabad",
        "Nainal",
        "Nainam",
        "Nainar",
        "Nainatown",
        "Nainaur",
        "Nainder",
        "Nainpur",
        "Naintal",
        "Nainwari",
        "Nair",
        "Nair",
        "Nairai",
        "Naira",
        "Nairam",
        "Nairaman",
        "Nairambag",
        "Nairampur",
        "Nairapur",
        "Nairassa",
        "Nairbandh",
        "Nairbari",
        "Nairbasti",
        "Nairbehera",
        "Nairbian",
        "Nairbilli",
        "Nairbok",
        "Nairboli",
        "Nairboli",
        "Nairbondi",
        "Nairbondih",
        "Nairbonji",
        "Nairbonn",
        "Nairbonna",
        "Nairbon",
        "Nairborda",
        "Nairbore",
        "Nairborg",
        "Nairborgo",
        "Nairbori",
        "Nairborn",
        "Nairborno",
        "Nairboron",
        "Nairbors",
        "Nairbort",
        "Nairbortu",
        "Nairboru",
        "Nairborui",
        "Nairbotis",
        "Nairbo",
        "Nairbou",
        "Nairboung",
        "Nairbouni",
        "Nairbounio",
        "Nairboum",
        "Nairbown",
        "Nairbownim",
        "Nairbox",
        "Nairbr",
        "Nairbre",
        "Nairbridge",
        "Nairbright",
        "Nairbrilla",
        "Nairbrill",
        "Nairbrillo",
        "Nairbrills",
        "Nairbrilly",
        "Nairbrillys",
        "Nairbrils",
        "Nairbrill",
        "Nairbris",
        "Nairbritt",
        "Nairbro",
        "Nairbrod",
        "Nairbrodden",
        "Nairbrode",
        "Nairbrodei",
        "Nairbroder",
        "Nairbrode",
        "Nairbrodi",
        "Nairbrodin",
        "Nairbroding",
        "Nairbrodo",
        "Nairbrodos",
        "Nairbrodosh",
        "Nairbrodosu",
        "Nairbros",
        "Nairbrot",
        "Nairbrote",
        "Nairbrotei",
        "Nairbroter",
        "Nairbrotero",
        "Nairbroteros",
        "Nairbroth",
        "Nairbrothi",
        "Nairbrothia",
        "Nairbrothiam",
        "Nairbrothi",
        "Nairbrothys",
        "Nairbrotian",
        "Nairbrotian",
        "Nairbroti",
        "Nairbrotian",
        "Nairbrotians",
        "Nairbrotias",
        "Nairbrotician",
        "Nairbrotician",
        "Nairbrotic",
        "Nairbrotic",
        "Nairbrotician",
        "Nairbrotician",
        "Nairbrotician",
        "Nairbroticia",
        "Nairbrotician",
        "Nairbroto",
        "Nairbrotoi",
        "Nairbrotoics",
        "Nairbrotoin",
        "Nairbrotoin",
        "Nairbrotoinc",
        "Nairbrotoin",
        "Nairbrotoinas",
        "Nairbrotoinci",
        "Nairbrotoin",
        "Nairbrotoinct",
        "Nairbrotoin",
        "Nairbrotoin",
        "Nairbrotol",
        "Nairbrotolit",
        "Nairbrotolith",
        "Nairbrotolith",
        "Nairbrotolithin",
        "Nairbrotoliths",
        "Nairbrotolitho",
        "Nairbrotolio",
        "Nairbrotolicin",
        "Nairbrotolicia",
        "Nairbrotolioca",
        "Nairbrotoliocain",
        "Nairbrotoliocaine",
        "Nairbrotoliocain",
        "Nairbrotoliocaine",
        "Nairbrotoliocaines",
        "Nairbrotolion",
        "Nairbrotolions",
        "Nairbrotolios",
        "Nairbrotolios",
        "Nairbrotolis",
        "Nairbrotolism",
        "Nairbrotolista",
        "Nairbrotolisten",
        "Nairbrotolitises",
        "Nairbrotolitis",
        "Nairbrotolitos",
        "Nairbrotolit",
        "Nairbrotolite",
        "Nairbrotoliten",
        "Nairbrotolites",
        "Nairbrotolito",
        "Nairbrotolitoes",
        "Nairbrotolitons",
        "Nairbrotolitosin",
        "Nairbrotolitosis",
        "Nairbrotolitoses",
        "Nairbrotolitosis",
        "Nairbrotolon",
        "Nairbrototom",
        "Nairbrototons",
        "Nairbrotolons",
        "Nairbrotology",
        "Nairbrotoman",
        "Nairbrotomans",
        "Nairbrotomancy",
        "Nairbrotomancian",
        "Nairbrotomancians",
        "Nairbrotomania",
        "Nairbrotomanias",
        "Nairbrotomania",
        "Nairbrotomaniac",
        "Nairbrotomaniacs",
        "Nairbrotomanias",
        "Nairbrotomaniacs",
        "Nairbrotomans",
        "Nairbrotomania",
        "Nairbrotomanic",
        "Nairbrotoman",
        "Nairbrotomanias",
        "Nairbrotomnesia",
        "Nairbrotomnesic",
        "Nairbrotomnesis",
        "Nairbrotomnesic",
        "Nairbrotomneses",
        "Nairbrotomnesis",
        "Nairbrotomnesiaes",
        "Nairbrotomnetic",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomnetones",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
        "Nairbrotomneton",
      ],
    };
    return stateDistricts[state] || [];
  },

  // Get DISCOMs (Discoms are state electricity boards) by state and district
  getDISCOMs: (state, district) => {
    const discomMapping = {
      "Andhra Pradesh": {
        default: ["ANDHRA PRADESH EASTERN POWER DISTRIBUTION CO LTD (APEPDCL)"],
      },
      "Arunachal Pradesh": {
        default: ["ARUNACHAL PRADESH STATE ELECTRICITY REGULATORY COMMISSION"],
      },
      Assam: { default: ["ASSAM POWER DISTRIBUTION COMPANY LIMITED"] },
      Bihar: { default: ["BIHAR STATE POWER HOLDING COMPANY LIMITED"] },
      Chhattisgarh: {
        default: ["CHHATTISGARH STATE POWER DISTRIBUTION CO LTD (CSPDCL)"],
      },
      Goa: { default: ["GOA ELECTRICITY REGULATORY COMMISSION"] },
      Gujarat: {
        default: [
          "AHMEDABAD ELECTRICITY COMPANY LIMITED (AECL)",
          "DAKSHIN GUJARAT VIJ COMPANY LIMITED (DGVCL)",
          "MADHYA GUJARAT VIJ COMPANY LIMITED (MGVCL)",
          "MADHYANCHAL ELECTRICITY DISTRIBUTION CO. LIMITED (MEDCL)",
          "PASCHIM GUJARATI VIJ COMPANY LIMITED (PGVCL)",
          "UTTAR GUJARATI VIJ COMPANY LIMITED (UGVCL)",
        ],
      },
      Haryana: {
        default: [
          "DAKSHIN HARYANA BIJLI VITRAN NIGAM LIMITED (DHBVN)",
          "UTTAR HARYANA BIJLI VITRAN NIGAM LIMITED (UHBVN)",
        ],
      },
      "Himachal Pradesh": {
        default: ["HIMACHAL PRADESH STATE ELECTRICITY BOARD LIMITED (HPSEB)"],
      },
      Jharkhand: {
        default: ["JHARKHAND STATE POWER DISTRIBUTION COMPANY LIMITED (JSPDCL)"],
      },
      Karnataka: {
        default: [
          "KARNATAKA POWER DISTRIBUTION COMPANY LIMITED (KPDCL)",
          "BANGALORE ELECTRICITY SUPPLY COMPANY LIMITED (BESCOM)",
          "CHAMUNDESHWARI ELECTRICITY SUPPLY CORPORATION LIMITED (CESCOM)",
          "MANGALORE ELECTRICITY SUPPLY COMPANY LIMITED (MESCOM)",
          "HUBLI ELECTRICITY SUPPLY COMPANY LIMITED (HESCOM)",
        ],
      },
      Kerala: {
        default: ["KERALA STATE ELECTRICITY BOARD LIMITED (KSEB)"],
      },
      "Madhya Pradesh": {
        default: [
          "MADHYA PRADESH POORV KSHETRA VIDYUT VITRAN COMPANY LIMITED (MPPKVVCL)",
          "MADHYA PRADESH PASCHIM KSHETRA VIDYUT VITRAN COMPANY LIMITED (MPPKVVCL)",
          "MADHYA PRADESH MADHYA KSHETRA VIDYUT VITRAN COMPANY LIMITED (MPMKVVCL)",
        ],
      },
      Maharashtra: {
        default: [
          "MAHARASHTRA STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED (MSEDCL)",
          "TATA POWER DISTRIBUTION COMPANY LIMITED",
        ],
      },
      Manipur: {
        default: ["MANIPUR STATE ELECTRICITY REGULATORY COMMISSION"],
      },
      Meghalaya: { default: ["MEGHALAYA POWER DISTRIBUTION CORPORATION"] },
      Mizoram: { default: ["MIZORAM STATE ELECTRICITY REGULATORY COMMISSION"] },
      Nagaland: {
        default: ["NAGALAND STATE ELECTRICITY REGULATORY COMMISSION"],
      },
      Odisha: {
        default: [
          "ODISHA POWER DISTRIBUTION COMPANY LIMITED (SOUTHERN DISCOM)",
          "ODISHA POWER DISTRIBUTION COMPANY LIMITED (CENTRAL DISCOM)",
          "ODISHA POWER DISTRIBUTION COMPANY LIMITED (WESTERN DISCOM)",
        ],
      },
      Punjab: {
        default: [
          "PUNJAB STATE POWER DISTRIBUTION COMPANY LIMITED (PSPCL)",
        ],
      },
      Rajasthan: {
        default: [
          "RAJASTHAN DISCOMS (JDVVN, PĐVN, AVVN, HPECL)",
        ],
      },
      Sikkim: {
        default: ["SIKKIM STATE ELECTRICITY REGULATORY COMMISSION"],
      },
      "Tamil Nadu": {
        default: [
          "TAMIL NADU GENERATION AND DISTRIBUTION CORPORATION LIMITED (TANGEDCO)",
        ],
      },
      Telangana: {
        default: [
          "TELANGANA STATE SOUTHERN POWER DISTRIBUTION COMPANY LIMITED (TSSPDCL)",
          "TELANGANA STATE NORTHERN POWER DISTRIBUTION COMPANY LIMITED (TSNPDCL)",
        ],
      },
      Tripura: {
        default: ["TRIPURA STATE ELECTRICITY REGULATORY COMMISSION"],
      },
      "Uttar Pradesh": {
        default: [
          "PASCHIM UTTAR PRADESH BIJLI VITRAN NIGAM LIMITED (PUVVNL)",
          "POORV UTTAR PRADESH BIJLI VITRAN NIGAM LIMITED (PUUVVNL)",
          "MADHYA UTTAR PRADESH BIJLI VITRAN NIGAM LIMITED (MUUVNL)",
          "DAKSHIN UTTAR PRADESH BIJLI VITRAN NIGAM LIMITED (DUUVNL)",
        ],
      },
      Uttarakhand: {
        default: ["UTTARAKHAND POWER CORPORATION LIMITED (UPCL)"],
      },
      "West Bengal": {
        default: [
          "WEST BENGAL STATE ELECTRICITY DISTRIBUTION COMPANY LIMITED (WBSEDCL)",
        ],
      },
    };

    const discomData = discomMapping[state];
    if (!discomData) return [];

    return discomData[district] || discomData.default || [];
  },
};

export default LocationService;
